//
// NOTE:
//  This build.gradle.kts is automatically generated by `generate-build-script.sh` (at `..`).
//  Do not try to make changes directly, at least before running build.
//  Before running the actual build, edit `build.gradle.kts.in` and regenerate script.
//  We have integrity check to error out if you do not follow the way.
//
