name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

    # Only for release tags
    - name: setup gpg necessities
      if: startsWith(github.ref, 'refs/tags/')
      run: sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
      env:
        GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
    - name: rewrite build.gradle.kts to require signing
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        sed -i "s/signing {}/signing { sign(publishing.publications) }/" ktmidi/build.gradle.kts
        sed -i "s/signing {}/signing { sign publishing.publications }/" ktmidi-jvm-desktop/build.gradle
        sed -i "s/signing {}/signing { sign(publishing.publications) }/" ktmidi-native-ext/build.gradle.kts

    # build or publish, depending on whether it is for release tags or not
    - name: build (ONLY FOR NON-RELEASES)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: ./gradlew --warning-mode all build
    - name: publish (ONLY FOR NEW RELEASE TAGS)
      if: startsWith(github.ref, 'refs/tags/')
      run: ./gradlew --warning-mode all build dokkaHtml publish
      env:
        USERNAME: atsushieno
        GITHUB_TOKEN: ${{ secrets.MAVEN_PAT }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

    - name: upload build failure logs
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-failure-logs
        path: |
          compose-audio-controls/build/reports/
          compose-audio-controls/*.log
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: ktmidi-artifacts
        path: |
          compose-audio-controls/build/libs/*.jar
          compose-audio-controls/build/outputs/aar/*.aar
          app/build/outputs/apk/debug/*.apk

    # Update API reference, 
    - name: deploy to GitHub Pages
      if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages
        folder: ktmidi/build/dokka/html
