name: build dist

on:
  push:
  pull_request:

jobs:
  build:
    name: build on macos-14
    runs-on: macos-14
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set up JDK 22
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 22

    - name: build
      run: ./gradlew --warning-mode all build

    - name: upload build failure logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-failure-logs
        path: |
          compose-audio-controls/build/reports/
          compose-audio-controls/*.log
          compose-audio-controls-midi/build/reports/
          compose-audio-controls-midi/*.log
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: library-artifacts
        path: |
          compose-audio-controls/build/libs/*.jar
          compose-audio-controls/build/outputs/aar/*.aar
          compose-audio-controls-midi/build/libs/*.jar
          compose-audio-controls-midi/build/outputs/aar/*.aar
          app/build/outputs/apk/debug/*.apk
