name: Publish
on:
  workflow_dispatch:

jobs:
  publish:
    name: Release build and publish
    runs-on: macos-14
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22

      - name: Publish to MavenCentral
        run: ./gradlew publishToMavenCentral dokkaHtml --no-configuration-cache --warning-mode all
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}

      # Update API reference
      # FIXME: we should probably publish compose-audio-controls-midi API too
      - name: deploy to GitHub Pages
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages
          folder: compose-audio-controls/build/dokka/html
